// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutOfOffice.Models;

namespace OutOfOffice.Migrations
{
    [DbContext(typeof(OutOfOfficeContext))]
    [Migration("20190703043539_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("OutOfOffice.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApproverEmail");

                    b.Property<string>("Email");

                    b.Property<DateTime>("LeaveDateTime");

                    b.Property<string>("Name");

                    b.Property<string>("Reason");

                    b.Property<string>("RequestType");

                    b.Property<DateTime>("ReturnDateTime");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("Request");
                });
#pragma warning restore 612, 618
        }
    }
}
